# Generated by Django 2.1.2 on 2018-11-23 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='Sistema/static/media/img_perros/noname.jpg', upload_to='Sistema/static/media/img_perros')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('razaMascota', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estadoMascota', models.CharField(default='Rescatado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombrePersona', models.CharField(max_length=30)),
                ('apellidoPersona', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('numeroFono', models.CharField(blank=True, max_length=10, null=True)),
                ('regionPersona', models.CharField(max_length=50)),
                ('ciudadPersona', models.CharField(max_length=50)),
                ('viviendaPersona', models.CharField(max_length=50)),
                ('tipoPersona', models.CharField(default='Usuario', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascotapersona',
            name='codigoPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Persona'),
        ),
    ]
