# Generated by Django 2.1.2 on 2018-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='constraseña',
            field=models.CharField(default='contraseña', max_length=20),
        ),
    ]
