# Generated by Django 2.1.2 on 2018-11-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_persona_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rutPersona',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
